### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by bim-g** [mmarcwabo/stock#1]
hello @mmarcwabo is it possible to update the documentation to make it easy to be used.

**Comment by mmarcwabo** [comment]
Hello @bim-g 
It has been a while. This is an old project, but why not?
Sure, I will revamp it.

**Comment by bim-g** [comment]
Ok, I see.

**Comment by bim-g** [comment]
A simple documentation will be helpful to anyone who will be interested by the  project

**Comment by mmarcwabo** [comment]
Revamp started.
